language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.6.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.3.3
      env: SYMFONY_VERSION=2.3.* COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_install:
  - composer self-update
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    
install: composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
